#!/bin/bash

# clean files and directories generated by run_all.sh
rm -rf data/circular_crop_dataset
rm -rf data/augmented_dataset
rm -rf data/combined_dataset
rm -rf current_data
rm -rf data_test
rm -rf trainedModels
rm -rf outputs_*
rm *.png
rm umap*.csv

